services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
